# render.yaml
# Tells Render how to deploy this app automatically

services:
  - type: web
    name: fraud-detection-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"